#!/usr/local/bin/php
<?php

function get_request()
{
    $headers = array();
    $ch = curl_init();
    curl_setopt_array($ch, array(
        CURLOPT_URL => "http://" . $_SERVER["AWS_LAMBDA_RUNTIME_API"] . "/2018-06-01/runtime/invocation/next",
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_HEADERFUNCTION => function ($curl, $header) use (&$headers) {
            $len = strlen($header);
            $header = explode(':', $header, 2);
            if (count($header) < 2)
                return $len;

            $headers[strtolower(trim($header[0]))][] = trim($header[1]);

            return $len;
        }
    ));

    $response = curl_exec($ch);
    curl_close($ch);

    $request = array(
        "body" => json_decode($response),
        "headers" => $headers
    );

    return $request;
}

function send_response($request, $body)
{
    $request_id = $request["headers"]["lambda-runtime-aws-request-id"][0];
    $ch = curl_init();
    curl_setopt_array($ch, array(
        CURLOPT_URL => "http://" . $_SERVER["AWS_LAMBDA_RUNTIME_API"] . "/2018-06-01/runtime/invocation/" . $request_id . "/response",
        CURLOPT_CUSTOMREQUEST => "POST",
        CURLOPT_POSTFIELDS => json_encode($body)
    ));

    curl_exec($ch);
    curl_close($ch);
}

require($_SERVER["LAMBDA_TASK_ROOT"] . "/index.php");

$request = get_request();
$response = handler($request);
send_response($request, $response);
